AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.6

require: rubocop-rails

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false
