AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.6

require: rubocop-rails

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false
